name: TEST
on: workflow_dispatch
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: my-step
        run: echo "Hello World!"
      - name: copy file via ssh key
        uses: appleboy/scp-action@v0.1.4
        with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USER }}
            passphrase: ${{ secrets.PASSPHRASE }}
            port: 22
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            source: "test.txt"
            target: /home/elijah
